# Generated by Django 4.2 on 2023-12-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0002_speciality_delete_newclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Sum_Scores', models.FloatField()),
                ('Count_Scores', models.FloatField()),
                ('Specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Bimar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.patient')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.doctor')),
            ],
        ),
    ]
