# Generated by Django 4.2 on 2023-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0003_doctor_patient_reserve_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Count_Scores',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Sum_Scores',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
