# Generated by Django 4.2 on 2023-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0004_alter_doctor_count_scores_alter_doctor_sum_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Count_Scores',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Count_Score',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
