# Generated by Django 4.2 on 2023-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0006_rename_count_score_doctor_count_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Average_Score',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
